### ISSUE TITLE
ZodError during deploy - expected array received undefined

### ISSUE THREAD

**Issue by rblaine95** [didx-xyz/ssi-trust-registry#67]
The deployment for the merge of #63 is experiencing the following error causing it to roll back automatically:
```
[2023-08-24T07:56:52.874Z] [main.js] [info]: Starting app with the following config 
{
  "server": {
    "port": 3000,
    "url": "http://0.0.0.0"
  },
  "logger": {
    "logLevel": "http",
    "outputFormat": "cli"
  },
  "db": {
    "connectionString": "mongodb+srv://mongo:*****@ssi-trust-registry.rww3zgq.mongodb.net/?retryWrites=true&w=majority",
    "name": "trust-registry"
  }
}
[2023-08-24T07:56:52.879Z] [database.js] [info]: Connecting to database... 
[2023-08-24T07:56:53.223Z] [database.js] [info]: Connected to database 'trust-registry' 
[2023-08-24T07:56:53.251Z] [mongoRepository.js] [info]: Index for schema document 'id' created: 
"id_1"
[2023-08-24T07:56:53.270Z] [mongoRepository.js] [info]: Index for subject document 'id' created 
"id_1"
[2023-08-24T07:56:53.279Z] [service.js] [info]: Importing schema at index 0 
{
  "schemaId": "2NPnMDv5Lh57gVZ3p3SYu3:2:e-KYC:1.0.0",
  "name": "Digital Identity"
}
[2023-08-24T07:56:53.336Z] [service.js] [info]: Schema 2NPnMDv5Lh57gVZ3p3SYu3:2:e-KYC:1.0.0 has been updated 
[2023-08-24T07:56:53.337Z] [service.js] [info]: Importing entity 8fa665b6-7fc5-4b0b-baee-6221b1844ec8 
{
  "id": "8fa665b6-7fc5-4b0b-baee-6221b1844ec8",
  "name": "Absa",
  "dids": [
    "did:indy:sovrin:2NPnMDv5Lh57gVZ3p3SYu3",
    "did:indy:sovrin:staging:C279iyCR8wtKiPC8o9iPmb"
  ],
  "logo_url": "https://s3.eu-central-1.amazonaws.com/builds.eth.company/absa.svg",
  "domain": "www.absa.africa",
  "role": [
    "issuer"
  ],
  "credentials": [
    "2NPnMDv5Lh57gVZ3p3SYu3:2:e-KYC:1.0.0"
  ]
}
/app/node_modules/zod/lib/types.js:43
                const error = new ZodError_1.ZodError(ctx.common.issues);
                              ^

ZodError: [
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "undefined",
    "path": [
      "dids"
    ],
    "message": "Required"
  }
]
    at get error [as error] (/app/node_modules/zod/lib/types.js:43:31)
    at ZodObject.parse (/app/node_modules/zod/lib/types.js:142:22)
    at Object.<anonymous> (/app/build/entity/mongoRepository.js:44:43)
    at Generator.next (<anonymous>)
    at fulfilled (/app/build/entity/mongoRepository.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  issues: [
    {
      code: 'invalid_type',
      expected: 'array',
      received: 'undefined',
      path: [ 'dids' ],
      message: 'Required'
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      code: 'invalid_type',
      expected: 'array',
      received: 'undefined',
      path: [ 'dids' ],
      message: 'Required'
    }
  ]
}

Node.js v18.17.1
```

**Comment by jakubkoci** [comment]
Ah, I see, that's because I changed the structure and therefore a validation that's applied for existing entries. Could we just remove the database for now? Later, we'll add some migration scripts to prevent such issues.

**Comment by rblaine95** [comment]
I'll reset the DB to zero

**Comment by rblaine95** [comment]
I've reset the DB and re-ran the last CD, looks like it's happy again
